apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: booking-service
  labels:
    name: test
spec:
  containers:
  - name: test
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 5000
  tolerations:
        - key: "os"
          operator: "Equal"
          value: "linux"
          effect: "NoSchedule"
