apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
 name: certissuer-letsencrypt
 namespace: istio-system
spec:
 acme:
  server: https://acme-staging-v02.api.letsencrypt.org/directory #https://acme-v02.api.letsencrypt.org/directory
  email: wxztechpass@outlook.com
  privateKeySecretRef:
    name: certissuer-letsencrypt
  solvers:
    - dns01:
        azureDNS:
          hostedZoneName: myhandymanpro.net
          resourceGroupName: rg-k8s-learning
          subscriptionID: ee611083-4581-4ba1-8116-a502d4539206
          environment: AzurePublicCloud
          managedIdentity:
            clientID: 47c5e7af-f537-49c9-9a6a-851b881a4d4e