apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvcAzFileLog.name }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: {{ .Values.pvAzFileLog.name }}
  resources:
    requests:
      storage: 5Gi