apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: inbound-allow-handymantracker
 namespace: handyman-tracker
spec:
  selector:
    matchLabels:
      app: handyman-tracker
  rules:
  - from:
    - source:
        namespaces: ["booking-service", "istio-system"] #allow istio-system due to traffic from Gateway in istio-system
  - to:
    - operation:
        paths: ["/*"]
        methods: ["*"]
        ports: ["443", "80"]
  action: ALLOW