apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .Values.httproute.name }}
  namespace: {{ .Values.namespace }}
spec:
  parentRefs:
  {{- range $v := .Values.httproute.parentRefs }}
  - name: {{ $v.name }}
    namespace: {{ $v.namespace }}
  {{- end }}
  hostnames: 
    {{- range $v := .Values.httproute.hostnames }}
    - {{ $v.name }}
    {{- end }}
  rules:
    - filters:
      - type: URLRewrite
        urlRewrite:
          hostname: elsewhere.example
      backendRefs:
      - name: example-svc
        weight: 1
        port: 80