apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
  name: {{ .Values.pvAzFileLog.name }}
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: fs-logs  # make sure this volumeid is unique for every identical share in the cluster
    volumeAttributes:
      resourceGroup: {{ .Values.pvAzFileLog.resourceGroup }}  # optional, only set this when storage account is not in the same resource group as node
      shareName: {{ .Values.pvAzFileLog.shareName }}
    nodeStageSecretRef:
      name: {{ .Values.pvAzFileLog.secretRefName }}
      namespace: {{ .Values.namespace }}
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=0
    - gid=0
    - mfsymlinks
    - cache=strict
    - nosharesock
    - nobrl