
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev-users-booking-service
  namespace: booking-service
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]